spring:
  application:
    name: passcard
  main:
    banner-mode: off
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 3001
  error:
    whitelabel:
      enabled: false
    path: /error

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    web: DEBUG
    org.springframework.web: DEBUG